"""
The consolidated shell.

This application accumulated thirty-one separate pages in the navigation
-- seven of them differing only in which file input they showed. That is
not a lot of capability, it is one capability spread thin, and it made a
small app feel unusable.

Three pages replace most of it:

    /add        one page for every kind of source
    /analyse    the local analysis tools, in tabs rather than scattered
    /toolkit    the standalone components, presented honestly as components

Nothing was deleted. The older routes still work and still have their
tests; they are simply no longer the way in.
"""
from __future__ import annotations

from flask import Blueprint, render_template, request
from flask_login import current_user, login_required

from .services import entry_manager, source_store

bp = Blueprint("main", __name__)


# The seven ingestion types, described the way a person would choose
# between them rather than by the file format they happen to use.
SOURCE_TYPES = [
    {
        "kind": "text",
        "label": "Text",
        "hint": "Paste anything written.",
        "input": "textarea",
        "field": "input_text",
    },
    {
        "kind": "pdf",
        "label": "PDF",
        "hint": "A report, paper or scanned document with selectable text.",
        "input": "file",
        "field": "pdf",
        "accept": "application/pdf",
    },
    {
        "kind": "article",
        "label": "Web page",
        "hint": "An article or blog post. The page is fetched and the body extracted.",
        "input": "url",
        "field": "url",
    },
    {
        "kind": "youtube",
        "label": "YouTube",
        "hint": "Uses captions where they exist, otherwise the video itself.",
        "input": "url",
        "field": "url_youtube",
    },
    {
        "kind": "audio",
        "label": "Audio",
        "hint": "Record here, or upload a voice memo, lecture or meeting.",
        "input": "file",
        "field": "audio",
        "accept": "audio/*",
        "recorder": "audio",
    },
    {
        "kind": "image",
        "label": "Image",
        "hint": "Photograph a page or whiteboard, or upload a chart or receipt.",
        "input": "file",
        "field": "image",
        "accept": "image/*",
        "recorder": "image",
    },
    {
        "kind": "video",
        "label": "Video",
        "hint": "Record a clip, or upload a screen recording.",
        "input": "file",
        "field": "video",
        "accept": "video/*",
        "recorder": "video",
    },
]

IMAGE_MODES = [
    ("describe", "Describe it"),
    ("extract_text", "Pull out the text"),
    ("receipt", "Itemise a receipt"),
    ("chart", "Explain a chart"),
    ("whiteboard", "Transcribe handwriting"),
]

# Components that are genuinely separate pieces rather than steps in the
# main flow. Grouped here instead of competing for space in the menu.
TOOLKIT = [
    {
        "endpoint": "v2.canvas_page",
        "name": "Canvas",
        "summary": "An infinite pan-and-zoom board for arranging documents spatially, with force-directed auto-layout.",
        "built": "Fruchterman-Reingold layout, level-of-detail rendering and viewport culling, written against the 2D canvas API.",
    },
    {
        "endpoint": "v2.reader_page",
        "name": "Speed reader",
        "summary": "Presents one word at a time at a fixed focal point, with pacing that adapts to measured comprehension.",
        "built": "Optimal-recognition-point alignment, punctuation-aware pacing, and comprehension questions generated by cloze deletion rather than by a model.",
    },
    {
        "endpoint": "v2.audio_lab_page",
        "name": "Audio fingerprints",
        "summary": "Identifies whether a recording has been seen before, and finds segments that repeat inside it.",
        "built": "The constellation algorithm: STFT, spectral peak picking, combinatorial hashing, and offset histogramming — robust to noise and re-encoding, unlike a file hash.",
    },
    {
        "endpoint": "v2.vault_page",
        "name": "Encrypted notes",
        "summary": "Notes encrypted in the browser. The server stores ciphertext it has no key for.",
        "built": "AES-256-GCM with PBKDF2 key derivation at 600,000 iterations, via WebCrypto. The passphrase never leaves the page.",
    },
    {
        "endpoint": "v2.rooms_page",
        "name": "Shared reading",
        "summary": "Several people annotating one document at once, with presence and live cursors.",
        "built": "Server-sent events with reconnection and replay from the last event id, over plain Flask with no extra dependency.",
    },
    {
        "endpoint": "v2.automation_page",
        "name": "Rules",
        "summary": "Conditions you write that run against new material without you watching.",
        "built": "A hand-written tokenizer and recursive-descent parser with its own evaluator — no eval(), and a static analyser that rejects catastrophic-backtracking regexes.",
    },
    {
        "endpoint": "matters.matter_list",
        "name": "Sealed records",
        "summary": "Records hashed on entry into an append-only chain, exportable with a standalone verifier.",
        "built": "A SHA-256 hash chain and Merkle tree, with membership proofs that confirm one record without disclosing the others.",
    },
]

ANALYSIS_TABS = [
    {"id": "trace", "label": "Trace a summary", "endpoint": "v2.trace_page",
     "summary": "Map each sentence of a summary back to the passage of the original it came from."},
    {"id": "chronology", "label": "Chronology", "endpoint": "v2.timeline_page",
     "summary": "Every date mentioned across your sources, in order."},
    {"id": "conflicts", "label": "Conflicting figures", "endpoint": "v2.contradictions_page",
     "summary": "Where two sources state a different number for the same thing."},
    {"id": "compare", "label": "Compare sources", "endpoint": "routes.compare",
     "summary": "Several sources side by side as a table, with agreements and disagreements separated."},
    {"id": "graph", "label": "Connections", "endpoint": "routes.graph_page",
     "summary": "How the things you've saved relate to one another."},
]


@bp.get("/add")
@login_required
def add_source():
    """One page for every kind of source.

    Previously seven near-identical pages, which made the application
    look larger and more confusing than it is. The type selector changes
    one input; everything else on the page stays put.
    """
    return render_template(
        "add.html",
        source_types=SOURCE_TYPES,
        image_modes=IMAGE_MODES,
        preselected=request.args.get("kind", "text"),
    )


@bp.get("/analyse")
@login_required
def analyse():
    return render_template(
        "analyse.html",
        tabs=ANALYSIS_TABS,
        stats=entry_manager.library_stats(current_user.id),
    )


@bp.get("/toolkit")
@login_required
def toolkit():
    return render_template(
        "toolkit.html",
        components=TOOLKIT,
        storage=source_store.storage_usage(current_user.id),
    )
